# Generated by Django 5.2.12 on 2026-04-18 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visa_type', models.CharField(choices=[('tourist', 'Tourist'), ('business', 'Business'), ('transit', 'Transit'), ('religious', 'Religious')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('processing_days', models.IntegerField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visa"."applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.TextField()),
                ('nationality', models.CharField(max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('scan_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visa"."passports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tourist_Pass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_code', models.TextField(unique=True)),
                ('qr_data', models.TextField()),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=50)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visa"."tourist_pass',
                'managed': False,
            },
        ),
    ]
