# Generated by Django 5.2.12 on 2026-04-18 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'Paypal'), ('cash', 'Cash'), ('other', 'Other')], max_length=50)),
                ('provider_ref', models.TextField(blank=True, null=True)),
                ('reference_type', models.TextField(blank=True, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment"."transactions',
                'managed': False,
            },
        ),
    ]
