# Generated by Django 5.2.12 on 2026-04-18 17:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(db_column='password_hash')),
                ('full_name', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('tourist', 'tourist'), ('guide', 'Guide'), ('admin', 'Admin')], default='tourist', max_length=21)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'accounts"."users',
                'managed': False,
            },
        ),
    ]
