class CountryData {
  static const Map<String, String> isoToName = {
    "AFG": "Afghan",
    "ALB": "Albanian",
    "DZA": "Algerian",
    "AND": "Andorran",
    "AGO": "Angolan",
    "ARG": "Argentinian",
    "ARM": "Armenian",
    "AUS": "Australian",
    "AUT": "Austrian",
    "AZE": "Azerbaijani",
    "BHR": "Bahraini",
    "BGD": "Bangladeshi",
    "BEL": "Belgian",
    "BRA": "Brazilian",
    "BGR": "Bulgarian",
    "CAN": "Canadian",
    "CHN": "Chinese",
    "COL": "Colombian",
    "HRV": "Croatian",
    "CUB": "Cuban",
    "CYP": "Cypriot",
    "CZE": "Czech",
    "DNK": "Danish",
    "EGY": "Egyptian",
    "EST": "Estonian",
    "ETH": "Ethiopian",
    "FIN": "Finnish",
    "FRA": "French",
    "GEO": "Georgian",
    "DEU": "German",
    "GRC": "Greek",
    "HUN": "Hungarian",
    "ISL": "Icelandic",
    "IND": "Indian",
    "IDN": "Indonesian",
    "IRN": "Iranian",
    "IRQ": "Iraqi",
    "IRL": "Irish",
    "ITA": "Italian",
    "JPN": "Japanese",
    "JOR": "Jordanian",
    "KAZ": "Kazakhstani",
    "KWT": "Kuwaiti",
    "LBN": "Lebanese",
    "LBY": "Libyan",
    "MYS": "Malaysian",
    "MEX": "Mexican",
    "MAR": "Moroccan",
    "NLD": "Dutch",
    "NZL": "New Zealander",
    "NOR": "Norwegian",
    "OMN": "Omani",
    "PAK": "Pakistani",
    "PSE": "Palestinian",
    "PHL": "Filipino",
    "POL": "Polish",
    "PRT": "Portuguese",
    "QAT": "Qatari",
    "ROU": "Romanian",
    "RUS": "Russian",
    "SAU": "Saudi Arabian",
    "SRB": "Serbian",
    "SGP": "Singaporean",
    "SVK": "Slovak",
    "ESP": "Spanish",
    "SDN": "Sudanese",
    "SWE": "Swedish",
    "CHE": "Swiss",
    "SYR": "Syrian",
    "TUN": "Tunisian",
    "TUR": "Turkish",
    "UKR": "Ukrainian",
    "ARE": "Emirati",
    "GBR": "British",
    "USA": "American",
    "YEM": "Yemeni",
    "VNM": "Vietnamese",
    "ZAF": "South African",
    "KOR": "South Korean",
    "THA": "Thai"
  };

  static List<String> get allNationalities => isoToName.values.toList()..sort();
}
