# Generated by Django 5.2.12 on 2026-04-18 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('hotel', 'Hotel'), ('tour', 'Tour'), ('transport', 'Transport')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking"."bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel_Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('nights', models.PositiveIntegerField()),
                ('guests', models.PositiveIntegerField(default=1)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
            ],
            options={
                'db_table': 'booking"."hotel_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour_Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('tour_date', models.DateField()),
            ],
            options={
                'db_table': 'booking"."tour_bookings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transport_Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('travel_date', models.DateField()),
                ('pickup_location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking"."transport_bookings',
                'managed': False,
            },
        ),
    ]
